# Generated by Django 3.1.7 on 2021-09-22 02:20

import applications.learning_object.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('path_origin', models.CharField(max_length=100)),
                ('path_adapted', models.CharField(max_length=100)),
                ('user_ref', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to=applications.learning_object.models.directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2021, 9, 22, 21, 20, 6, 529598))),
            ],
            options={
                'db_table': 'learning_objects',
            },
        ),
    ]
