# Generated by Django 3.1.7 on 2021-10-08 06:25

import applications.learning_object.models
import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('path_origin', models.CharField(max_length=100)),
                ('path_adapted', models.CharField(max_length=100)),
                ('user_ref', models.CharField(max_length=100)),
                ('file_folder', models.CharField(max_length=100, null=True)),
                ('preview_origin', models.URLField(null=True)),
                ('preview_adapted', models.URLField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2021, 10, 9, 1, 25, 55, 542759))),
                ('file_adapted', models.FileField(blank=True, null=True, upload_to=applications.learning_object.models.directory_path)),
            ],
            options={
                'db_table': 'learning_objects',
            },
        ),
        migrations.CreateModel(
            name='PageLearningObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
                ('learning_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_object.learningobject')),
            ],
            options={
                'db_table': 'pages_oa',
            },
        ),
        migrations.CreateModel(
            name='TagPageLearningObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
                ('text', models.TextField(null=True)),
                ('html_text', models.TextField(null=True)),
                ('id_class_ref', models.CharField(max_length=20)),
                ('page_oa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_object.pagelearningobject')),
            ],
            options={
                'db_table': 'data_tag',
            },
        ),
        migrations.CreateModel(
            name='DataAtribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atribute', models.CharField(max_length=100)),
                ('data_atribute', models.CharField(max_length=100)),
                ('data_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_object.tagpagelearningobject')),
            ],
            options={
                'db_table': 'data_atribute',
            },
        ),
        migrations.CreateModel(
            name='AdaptationLearningObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('areas', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=6)),
                ('learning_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_object.learningobject')),
            ],
            options={
                'db_table': 'adaptations_learning_objects',
            },
        ),
    ]
