# Generated by Django 3.1.7 on 2021-11-12 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataattribute',
            name='path_preview',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dataattribute',
            name='path_system',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataattribute',
            name='source',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 13, 9, 9, 49, 605914)),
        ),
    ]
