# Generated by Django 3.2.7 on 2021-11-17 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningobject',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 18, 9, 12, 2, 381788)),
        ),
    ]
