# Generated by Django 3.1.7 on 2022-01-04 14:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagelearningobject',
            name='len_paths',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 4, 9, 47, 13, 241824, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 5, 9, 47, 13, 241824, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requestapi',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 4, 9, 47, 13, 245731, tzinfo=utc)),
        ),
    ]
