# Generated by Django 3.1.7 on 2021-10-21 22:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningobject',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 22, 17, 2, 30, 422714)),
        ),
        migrations.AlterField(
            model_name='tagpagelearningobject',
            name='page_learning_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='learning_object.pagelearningobject'),
        ),
    ]
