# Generated by Django 3.2.7 on 2021-09-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningobject',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
