# Generated by Django 3.2.7 on 2021-09-27 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningobject',
            name='file_folder',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='learningobject',
            name='preview_adapted',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='learningobject',
            name='preview_origin',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 28, 13, 15, 10, 187049)),
        ),
    ]
