# Generated by Django 3.1.7 on 2021-12-11 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('text_number', models.CharField(blank=True, max_length=100, null=True)),
                ('video_number', models.CharField(blank=True, max_length=100, null=True)),
                ('audio_number', models.CharField(blank=True, max_length=100, null=True)),
                ('img_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'metadata_info',
            },
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 12, 11, 36, 8, 382580)),
        ),
    ]
