# Generated by Django 3.1.7 on 2021-10-11 16:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningobject',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 12, 11, 46, 16, 107023)),
        ),
        migrations.AlterField(
            model_name='tagpagelearningobject',
            name='page_oa_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='learning_object.pagelearningobject'),
        ),
    ]
