# Generated by Django 3.1.7 on 2021-11-10 16:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningobject',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 11, 11, 56, 22, 687914)),
        ),
        migrations.AlterField(
            model_name='tagadapted',
            name='tag_page_learning_object',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='learning_object.tagpagelearningobject'),
        ),
    ]
