# Generated by Django 3.1.7 on 2021-11-12 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object', '0002_auto_20211112_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningobject',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 13, 9, 34, 16, 535560)),
        ),
    ]
