# Generated by Django 3.2.7 on 2021-12-14 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object', '0002_auto_20211210_1934'),
        ('learning_object', '0002_auto_20211211_1136'),
    ]

    operations = [
    ]
