# Generated by Django 3.1.7 on 2021-11-10 17:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object', '0002_auto_20211110_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningobject',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 11, 12, 14, 28, 292441)),
        ),
        migrations.AlterField(
            model_name='tagadapted',
            name='tag_page_learning_object',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags_adapted', to='learning_object.tagpagelearningobject'),
        ),
    ]
