# Generated by Django 3.2.7 on 2021-11-02 02:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object', '0002_alter_learningobject_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagadapted',
            name='path_system',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 2, 21, 31, 46, 509430)),
        ),
    ]
