# Generated by Django 3.1.7 on 2021-09-22 02:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object', '0002_auto_20210921_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningobject',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 22, 21, 22, 14, 450705)),
        ),
    ]
