# Generated by Django 3.2.7 on 2021-09-15 19:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object', '0002_learningobject_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningobject',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2258, 4, 6, 19, 11, 19, 962152, tzinfo=utc)),
        ),
    ]
