# Generated by Django 3.2.7 on 2021-09-27 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object', '0002_auto_20210927_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningobject',
            name='file',
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 28, 14, 40, 4, 46800)),
        ),
    ]
