# Generated by Django 3.2.7 on 2021-11-17 14:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object', '0002_alter_learningobject_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningobject',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 18, 9, 20, 32, 525538)),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='tag_adapted',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='learning_object.tagadapted'),
        ),
    ]
