# Generated by Django 3.2.7 on 2021-12-15 20:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object', '0003_merge_0002_auto_20211210_1934_0002_auto_20211211_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningobject',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 15, 15, 41, 4, 117853, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 16, 15, 41, 4, 117853, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='metadatainfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
