# Generated by Django 3.2.7 on 2021-09-24 16:47

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object', '0003_learningobject_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningobject',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 25, 11, 47, 55, 780027)),
        ),
        migrations.CreateModel(
            name='LearningObjectAdaptation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methods', models.CharField(max_length=10)),
                ('areas', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=4), size=4)),
                ('learning_objects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_object.learningobject')),
            ],
            options={
                'db_table': 'learning_objects_adaptations',
            },
        ),
    ]
