# Generated by Django 3.2.7 on 2021-10-03 22:33

import applications.learning_object.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object', '0003_auto_20210927_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningobject',
            name='file_adapted',
            field=models.FileField(null=True, upload_to=applications.learning_object.models.directory_path),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 4, 17, 33, 48, 761572)),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='preview_adapted',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='preview_origin',
            field=models.URLField(null=True),
        ),
    ]
