# Generated by Django 3.2.7 on 2021-11-05 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object', '0003_auto_20211101_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagadapted',
            name='button_audio_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tagadapted',
            name='button_text_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 6, 16, 57, 26, 368066)),
        ),
    ]
