# Generated by Django 3.2.7 on 2021-11-12 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object', '0003_auto_20211112_0918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataattribute',
            old_name='attribute',
            new_name='attribute',
        ),
        migrations.RenameField(
            model_name='dataattribute',
            old_name='data_atribute',
            new_name='data_attribute',
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 13, 13, 34, 34, 390654)),
        ),
    ]
