# Generated by Django 3.2.7 on 2021-11-17 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object', '0003_auto_20211117_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='path_preview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 18, 12, 9, 17, 661480)),
        ),
    ]
