# Generated by Django 3.1.7 on 2021-12-21 03:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object', '0003_auto_20211215_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagadapted',
            name='text_column',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tagadapted',
            name='text_row',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tagadapted',
            name='text_table',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 22, 9, 51, 781168)),
        ),
    ]
