# Generated by Django 3.2.7 on 2021-11-07 18:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object', '0004_auto_20211105_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagelearningobject',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 13, 50, 53, 814686)),
        ),
        migrations.AlterField(
            model_name='tagpagelearningobject',
            name='page_learning_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_object.pagelearningobject'),
        ),
    ]
