# Generated by Django 3.2.7 on 2021-11-12 20:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object', '0004_auto_20211112_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adaptationlearningobject',
            name='learning_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptation_learning_object', to='learning_object.learningobject'),
        ),
        migrations.AlterField(
            model_name='dataattribute',
            name='tag_page_learning_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='learning_object.tagpagelearningobject'),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 13, 15, 43, 12, 970131)),
        ),
        migrations.AlterField(
            model_name='pagelearningobject',
            name='learning_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_learning_object', to='learning_object.learningobject'),
        ),
        migrations.AlterField(
            model_name='tagpagelearningobject',
            name='page_learning_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_page_learning_object', to='learning_object.pagelearningobject'),
        ),
    ]
