# Generated by Django 3.2.7 on 2021-10-04 00:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object', '0004_auto_20211003_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningobject',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 4, 19, 54, 45, 427438)),
        ),
    ]
