# Generated by Django 3.2.7 on 2021-09-24 19:31

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object', '0004_auto_20210924_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningobject',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 25, 14, 31, 36, 460169)),
        ),
        migrations.AlterField(
            model_name='learningobjectadaptation',
            name='areas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=6),
        ),
    ]
