# Generated by Django 3.2.7 on 2021-12-25 14:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object', '0004_auto_20211215_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('institution', models.CharField(blank=True, max_length=100, null=True)),
                ('purpose_use', models.TextField()),
                ('api_key', models.TextField()),
            ],
            options={
                'db_table': 'request_api',
            },
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 25, 9, 33, 10, 539968, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 26, 9, 33, 10, 539968, tzinfo=utc)),
        ),
    ]
