# Generated by Django 3.2.7 on 2022-08-08 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object', '0004_auto_20220505_1224'),
        ('learning_object', '0004_auto_20220506_1006'),
    ]

    operations = [
    ]
