# Generated by Django 3.2.7 on 2021-10-16 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object', '0005_alter_learningobject_expires_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataatribute',
            old_name='data_tag_id',
            new_name='tag_page_learning_object',
        ),
        migrations.RenameField(
            model_name='tagpagelearningobject',
            old_name='page_oa_id',
            new_name='page_learning_object',
        ),
        migrations.AlterField(
            model_name='dataatribute',
            name='data_atribute',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 17, 10, 11, 30, 467670)),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='file_folder',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='path_adapted',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='path_origin',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
