# Generated by Django 3.1.7 on 2021-11-15 15:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object', '0005_auto_20211114_0157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataattribute',
            old_name='atribute',
            new_name='attribute',
        ),
        migrations.RenameField(
            model_name='dataattribute',
            old_name='data_atribute',
            new_name='data_attribute',
        ),
        migrations.AlterField(
            model_name='dataattribute',
            name='tag_page_learning_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='learning_object.tagpagelearningobject'),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 16, 10, 34, 14, 58289)),
        ),
    ]
