# Generated by Django 3.2.7 on 2021-11-07 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object', '0005_auto_20211107_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningobject',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 15, 23, 27, 381558)),
        ),
    ]
