# Generated by Django 3.2.7 on 2021-09-24 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object', '0005_auto_20210924_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningobjectadaptation',
            old_name='methods',
            new_name='method',
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 25, 16, 40, 14, 31926)),
        ),
    ]
