# Generated by Django 3.2.7 on 2021-09-24 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object', '0006_auto_20210924_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningobjectadaptation',
            old_name='learning_objects',
            new_name='learning_object',
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 25, 16, 43, 11, 438503)),
        ),
    ]
