# Generated by Django 3.1.7 on 2021-11-15 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object', '0006_auto_20211115_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningobject',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 16, 10, 40, 53, 32712)),
        ),
    ]
