# Generated by Django 3.2.7 on 2022-08-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object', '0006_pagelearningobject_is_webpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagelearningobject',
            name='file_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='pagelearningobject',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
