# Generated by Django 3.2.7 on 2022-01-01 21:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object', '0007_auto_20211226_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adaptationlearningobject',
            name='learning_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='adaptation_learning_object', to='learning_object.learningobject'),
        ),
        migrations.AlterField(
            model_name='dataattribute',
            name='tag_page_learning_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='attributes', to='learning_object.tagpagelearningobject'),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 1, 16, 22, 17, 277670, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 2, 16, 22, 17, 277670, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pagelearningobject',
            name='learning_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='page_learning_object', to='learning_object.learningobject'),
        ),
        migrations.AlterField(
            model_name='requestapi',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 1, 16, 22, 17, 280699, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tagadapted',
            name='tag_page_learning_object',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='tags_adapted', to='learning_object.tagpagelearningobject'),
        ),
        migrations.AlterField(
            model_name='tagpagelearningobject',
            name='page_learning_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='tag_page_learning_object', to='learning_object.pagelearningobject'),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='tag_adapted',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='transcript', to='learning_object.tagadapted'),
        ),
    ]
