# Generated by Django 3.2.7 on 2021-10-16 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object', '0007_auto_20211016_1528'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataAtribute',
            new_name='DataAttribute',
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 17, 15, 45, 18, 846308)),
        ),
    ]
