# Generated by Django 3.2.7 on 2022-01-02 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object', '0008_auto_20220101_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningobject',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 2, 12, 16, 21, 456370)),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 3, 12, 16, 21, 456370)),
        ),
        migrations.AlterField(
            model_name='requestapi',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 2, 12, 16, 21, 459370)),
        ),
    ]
