# Generated by Django 3.2.7 on 2022-08-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object', '0008_auto_20220826_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagadapted',
            name='img_fullscreen',
            field=models.BooleanField(default=False),
        ),
    ]
