# Generated by Django 3.2.7 on 2022-09-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object', '0009_tagadapted_img_fullscreen'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagpagelearningobject',
            name='adaptation',
            field=models.BooleanField(default=True),
        ),
    ]
