# Generated by Django 3.2.7 on 2021-10-20 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object', '0009_auto_20211020_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningobject',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 16, 11, 27, 313217)),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='file_adapted',
            field=models.URLField(null=True),
        ),
    ]
