# Generated by Django 3.2.7 on 2022-01-02 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object', '0009_auto_20220102_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningobject',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 2, 12, 46, 6, 222765)),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 3, 12, 46, 6, 222765)),
        ),
        migrations.AlterField(
            model_name='requestapi',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 2, 12, 46, 6, 225800)),
        ),
    ]
