# Generated by Django 3.2.7 on 2022-01-02 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object', '0011_auto_20220102_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningobject',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 3, 13, 2, 24, 589702)),
        ),
    ]
