# Generated by Django 3.2.7 on 2022-01-02 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object', '0012_alter_learningobject_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningobject',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 3, 13, 6, 57, 417160)),
        ),
    ]
