# Generated by Django 3.2.7 on 2022-01-02 18:11

import applications.learning_object.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object', '0013_alter_learningobject_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningobject',
            name='expires_at',
            field=models.DateTimeField(default=applications.learning_object.models.one_day_hence),
        ),
    ]
